### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [chapkachapka/charles-robert-maturin_melmoth-the-wanderer#1]
# General Issues:

- [x] re-run `se typogrify .` and commit the changes.

- [ ] Remove italics from `governante`. It is in MW.

- [x] For the headers in `<section>` elements, I recommend that you include the following text in the `<section>` elements. `<section>`s are used for "a major structural division in a work", not just for satisfying lint errors ([SEMOS 4.1.1.1.2](https://standardebooks.org/manual/1.7.4/single-page#4.1.1.1.2)). I understand that the sections actually extend over multiple chapters, but this structuring makes more sense semantically than only including the headers. You also need to remove `-header` from the `<section>` ids.

# preface.xhtml:

- [x] Remove the `<div>` element. You don't need it.

# chapter-1.xhtml:

- [x] `<i xml:lang="fr">Anglicè</i>` is actually Latin.

- [x] `<i xml:lang="fr">Hibernicè</i>` is also Latin.

- [x] Remove italics from `imprimis`. It is in MW.

- [x] Adjust the language tag for `<i xml:lang="ie">kish</i>` to be `xml:lang="ga"`.

# chapter-2.xhtml:

- [x] Adjust the language tag for `<span xml:lang="en-ie">gossoon</span>` to be `xml:lang="ga"`.

# chapter-3.xhtml:

- [x] You need a Latin language tag for the epigraph.

- [x] It looks like there is a typo in `<i xml:lang="fr">a l’outrance</i>`. It should be `à l’outrance`.

- [ ] Remove italics from `estrade`. It is in MW.

# chapter-4.xhtml:

- [x] Remove italics from `mutatis mutandis`. It is in MW.

# chapter-5.xhtml:

- [x] You need to mark the salutation in the first letter blockquote.

# chapter-7.xhtml:

- [ ] Remove italics from `agrémens`. It is in MW.

- [x] The `<blockquote>`s are missing letter samantics.

- [x] The signature needs sender semantics.

# chapter-9.xhtml:

- [x] `<i>Marmion</i>` needs `epub:type="se:name.publication.poem"` semantics.

# chapter-11.xhtml:

- [ ] Remove italics from `spicula`. it is in MW.

# chapter-12.xhtml:

- [x] `<i><abbr>St.</abbr> Patrick for Ireland</i>` needs `epub:type="se:name.publication.play"` semantics.

# chapter-39.xhtml:

- [x] In the epigraph, remove the period at the end of the `<cite>`.

# endnotes.xhtml:

- [x] In note 53, `<i xml:lang="la">apud</i> <i epub:type="se:name.publication.book">Don Quixote</i> <i xml:lang="la">de Collibus Ubedae</i>` can be simplified as `<i xml:lang="la">apud <i epub:type="se:name.publication.book">Don Quixote</i> de Collibus Ubedae</i>`.

**Comment by chapkachapka** [comment]
I've made these changes, except the following:

1. Governante, estrade, agrémens, and spicula are all in M-W but only in the unabridged version, with the "Love words?" block in each entry--per [8.2.9.2](https://standardebooks.org/manual/1.7.4/single-page#8.2.9.4), my understanding is this means they still get italics?

2. "Gossoon" isn't derived from Irish, it's an adaptation of the Norman French "garçun," from which we also get the modern French "garçon". It's a well-established regional English word rather than a loan word; I tagged it with an en-IE span but no italics. The "ga" language tag would make a screen reader try to pronounce it as if it's correctly spelled Irish, which it isn't. If you don't like the "en-IE" tag I think it would be better to remove the span completely.

3. "Kish" is another one--you're right that "ie" is the wrong tag, but I meant to tag it as "en-IE". It is borrowed from the Irish "cis" but can't be tagged "ga" for the same reason as gossoon--there's no letter K in Irish, to start with. For this one, if you don't like the "en-IE" tag, it'd be better in my opinion to leave it as unsemanticated italics per [8.2.10.1](https://standardebooks.org/manual/1.7.4/single-page#8.2.10.1). (This is common practice for Irish writers of this period when writing for mostly English audiences).

**Comment by EmmaSweeney** [comment]
1.  All those words are found in the basic version of MW, which uses the link `https://www.merriam-webster.com/dictionary/WORD`. You can also find the words in the basic dictionary by browsing the list of words with the link `https://www.merriam-webster.com/browse/dictionary/`. 
The Medical Dictionary uses the link `https://www.merriam-webster.com/medical/WORD` and the Unabridged Dictionary uses the link `https://unabridged.merriam-webster.com/unabridged/WORD`.
Those words should not be italicized. "Love Words?" is just a promo.

3. Remove the language tag.

4. Remove the language tag.

**Comment by chapkachapka** [comment]
I've removed the language tags.

For the other issue--are you sure? The "Love Words?" text says that the word you've searched for is "only in the M-W Unabridged Dictionary" and I've been told specifically by other editors on other projects that this doesn't count as being in the basic version for 8.2.9.2. I did a quick search of the mailing list and found a bunch of posts to that effect, saying that if you see the "Love Words" block it means it's only in the unabridged dictionary and you should italicise it.

**Comment by EmmaSweeney** [comment]
Ok, leave them as is.

I'll review this again later in the week.

**Comment by EmmaSweeney** [comment]
A few more issues:

- [x] You are missing the first bit of CSS for all epigraphs ([SEMOS 7.4.1](https://standardebooks.org/manual/1.7.4/single-page#7.4.1)).

- [x] You also need to add CSS for epigraphs in section headers ([SEMOS 7.4.5.2](https://standardebooks.org/manual/1.7.4/single-page#7.4.5.2)).

**Comment by chapkachapka** [comment]
Done and done.
